# Generated by Django 4.1.4 on 2023-01-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('chq', models.CharField(default='C->', max_length=10)),
                ('bank', models.CharField(choices=[('SBI', 'SBI'), ('Bandhan Bank', 'Bandhan Bank'), ('HDFC Bank', 'HDFC Bank'), ('IDBI Bank', 'IDBI Bank'), ('Axis Bank', 'Axis Bank'), ('Union Bank of India', 'Union Bank of India'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('Indian Bank', 'Indian Bank'), ('Punjab National bank', 'Punjab National bank')], max_length=50)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Cleared', 'Cleared'), ('Bounced', 'Bounced'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('agent', models.CharField(choices=[('Goutam Halder', 'Goutam Halder'), ('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Jeet Roy', 'Jeet Roy')], max_length=25)),
                ('remarks', models.CharField(default='N/A', max_length=200)),
            ],
        ),
    ]
