# Generated by Django 4.1.5 on 2023-02-04 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0003_master_date_alter_master_agent_alter_master_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='date',
        ),
    ]
