# Generated by Django 4.1.4 on 2023-02-05 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0008_alter_master_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
