# Generated by Django 4.1.4 on 2023-02-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0011_alter_master_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='date',
        ),
    ]
