# Generated by Django 4.1.5 on 2023-02-07 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0012_remove_master_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
