# Generated by Django 4.1.6 on 2023-02-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0014_order_alter_master_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
