# Generated by Django 4.1.6 on 2023-02-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0015_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shop_name', models.CharField(max_length=80)),
                ('invoice', models.CharField(default='I->', max_length=8)),
                ('amount', models.IntegerField()),
                ('agent', models.CharField(max_length=25)),
                ('deliverysts', models.CharField(max_length=25)),
                ('paymentsts', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=120)),
            ],
        ),
    ]
