# Generated by Django 4.1.6 on 2023-02-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0016_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(max_length=12),
        ),
    ]
