# Generated by Django 4.1.6 on 2023-02-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0019_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='bank',
            field=models.CharField(choices=[('State Bank of India', 'State Bank of India'), ('Bandhan Bank', 'Bandhan Bank'), ('HDFC Bank', 'HDFC Bank'), ('IDBI Bank', 'IDBI Bank'), ('Axis Bank', 'Axis Bank'), ('Union Bank of India', 'Union Bank of India'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('Indian Bank', 'Indian Bank'), ('Punjab National bank', 'Punjab National bank'), ('Bank of Baroda', 'Bank of Baroda'), ('Indian Overseas Bank', 'Indian Overseas Bank'), ('Central Bank of India', 'Central Bank of India'), ('Canara Bank', 'Canara Bank'), ('UCO Bank', 'UCO Bank'), ('ICICI Bank', 'ICICI Bank'), ('IDFC FIRST Bank', 'IDFC FIRST Bank')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='agent',
            field=models.CharField(choices=[('Goutam Halder', 'Goutam Halder'), ('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Jeet Roy', 'Jeet Roy'), ('Raju Barui', 'Raju Barui')], max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverysts',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Undelivered', 'Undelivered')], max_length=25),
        ),
    ]
