# Generated by Django 4.1.6 on 2023-02-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0020_alter_master_bank_alter_order_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentsts',
            field=models.CharField(choices=[('Cash Given', 'Cash Given'), ('Ondate Cheque Given', 'Ondate Cheque Given'), ('Postdate Cheque Given', 'Postdate Cheque Given'), ('Online NEFT', 'Online NEFT'), ('UPI Payment', 'UPI Payment'), ('No payment', 'No payment')], max_length=50),
        ),
    ]
