# Generated by Django 4.1.6 on 2023-02-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0021_alter_order_paymentsts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryagt',
            field=models.CharField(choices=[('Kaka', 'Kaka'), ('Raju Barui', 'Raju Barui')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverysts',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Not Delivered', 'Not Delivered')], max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentsts',
            field=models.CharField(choices=[('Cash Given', 'Cash Given'), ('Ondate Cheque Given', 'Ondate Cheque Given'), ('Postdate Cheque Given', 'Postdate Cheque Given'), ('Online NEFT', 'Online NEFT'), ('UPI Payment', 'UPI Payment'), ('No Payment', 'No Payment')], max_length=50),
        ),
    ]
