# Generated by Django 4.1.6 on 2023-02-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0022_order_deliveryagt_alter_order_deliverysts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryagt',
            field=models.CharField(choices=[('Kaka', 'Kaka'), ('Raju Barui', 'Raju Barui')], max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.CharField(default='I->', max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.CharField(default='N/A', max_length=120),
        ),
    ]
