# Generated by Django 4.1.6 on 2023-02-16 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0023_alter_order_deliveryagt_alter_order_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('recv_challan', models.CharField(blank=True, max_length=8)),
                ('client', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=30)),
                ('qty', models.IntegerField()),
                ('agent', models.CharField(choices=[('Goutam Halder', 'Goutam Halder'), ('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Jeet Roy', 'Jeet Roy'), ('Raju Barui', 'Raju Barui')], max_length=25)),
                ('status', models.CharField(choices=[('Goutam Halder', 'Goutam Halder'), ('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Jeet Roy', 'Jeet Roy'), ('Raju Barui', 'Raju Barui')], max_length=15)),
                ('issue', models.CharField(blank=True, max_length=30)),
                ('delv_doc', models.CharField(blank=True, max_length=10)),
                ('delv_date', models.CharField(blank=True, max_length=12)),
                ('remarks', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.CharField(blank=True, default='N/A', max_length=120),
        ),
    ]
