# Generated by Django 4.1.6 on 2023-02-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0024_replacement_alter_order_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliverysts',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Not Delivered', 'Not Delivered'), ('Cancelled', 'Cancelled')], max_length=25),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('CN Given', 'CN Given'), ('Item Given', 'Item Given'), ('DOA Received', 'DOA Received'), ('DOA Given', 'DOA Given')], max_length=15),
        ),
    ]
