# Generated by Django 4.1.6 on 2023-02-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0025_alter_order_deliverysts_alter_replacement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='issue',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
