# Generated by Django 4.1.6 on 2023-02-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0026_alter_replacement_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
