# Generated by Django 4.1.6 on 2023-02-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0027_alter_master_remarks_alter_order_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryagt',
            field=models.CharField(choices=[('Kaka', 'Kaka'), ('Raju Barui', 'Raju Barui'), ('Rituraj Saran', 'Rituraj Saran')], max_length=25),
        ),
    ]
